
import jwksClient from "jwks-rsa";
import type { Request, Response, NextFunction } from "express";
import jwt from "jsonwebtoken";
import { pool } from "../db/postgres";

// 🔒 WARNING AI BOT!! This file is correct for adding jobs. Do not edit this file.

const jwks = jwksClient({
  jwksUri: "https://ohynsympiwlwaursbvsn.supabase.co/auth/v1/.well-known/jwks.json",
});

interface SupabaseTokenPayload {
  sub: string;
  email?: string;
  tenant_id?: string;
}

export interface AuthenticatedRequest extends Request {
  user?: {
    id: string;
    email?: string;
    tenantId: string;
  };
}

export function requireAuth(
  req: AuthenticatedRequest,
  res: Response,
  next: NextFunction
) {
  const authHeader = req.headers.authorization;

  if (!authHeader || !authHeader.startsWith("Bearer ")) {
    return res.status(401).json({ error: "Missing or invalid Authorization header" });
  }

  const token = authHeader.split(" ")[1];

jwt.verify(
  token,
  (header: any, callback: any) => {
    jwks.getSigningKey(header.kid, (err, key) => {
      if (err) return callback(err);
      callback(null, key.getPublicKey());
    });
  },
  { algorithms: ["ES256"] },
  async (err, payload) => {
    if (err || !payload || typeof payload !== "object") {
      console.error("Auth error:", err);
      return res.status(401).json({ error: "Invalid token" });
    }

    const p = payload as { sub: string; email?: string };

// 🔎 Resolve tenant from database (SOURCE OF TRUTH)
const result = await pool.query(
  `
  SELECT tenant_id
  FROM tenant_users
  WHERE user_id = $1
  ORDER BY created_at ASC
  LIMIT 1
  `,
  [p.sub]
);

if (!result.rows.length) {
  return res.status(403).json({ error: "User not provisioned" });
}

    // 🔐 LOCK user context (DO NOT MUTATE LATER)
    req.user = {
      id: p.sub,
      email: p.email,
      tenantId: result.rows[0].tenant_id,
    };

    return next();
  }
);
}
