/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_supabase-test`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/components/crew/CrewManager`; params?: Router.UnknownInputParams; } | { pathname: `/main/add-job`; params?: Router.UnknownInputParams; } | { pathname: `/main/edit-tabs`; params?: Router.UnknownInputParams; } | { pathname: `/main`; params?: Router.UnknownInputParams; } | { pathname: `/main/jobs`; params?: Router.UnknownInputParams; } | { pathname: `/main/settings`; params?: Router.UnknownInputParams; } | { pathname: `/main/tasks`; params?: Router.UnknownInputParams; } | { pathname: `/main/templates`; params?: Router.UnknownInputParams; } | { pathname: `/main/vendors`; params?: Router.UnknownInputParams; } | { pathname: `/crew/job/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/job/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/job/[id]/notes`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/job/[id]/send-links`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_supabase-test`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/components/crew/CrewManager`; params?: Router.UnknownOutputParams; } | { pathname: `/main/add-job`; params?: Router.UnknownOutputParams; } | { pathname: `/main/edit-tabs`; params?: Router.UnknownOutputParams; } | { pathname: `/main`; params?: Router.UnknownOutputParams; } | { pathname: `/main/jobs`; params?: Router.UnknownOutputParams; } | { pathname: `/main/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/main/tasks`; params?: Router.UnknownOutputParams; } | { pathname: `/main/templates`; params?: Router.UnknownOutputParams; } | { pathname: `/main/vendors`; params?: Router.UnknownOutputParams; } | { pathname: `/crew/job/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/job/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/job/[id]/notes`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/job/[id]/send-links`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_supabase-test${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/components/crew/CrewManager${`?${string}` | `#${string}` | ''}` | `/main/add-job${`?${string}` | `#${string}` | ''}` | `/main/edit-tabs${`?${string}` | `#${string}` | ''}` | `/main${`?${string}` | `#${string}` | ''}` | `/main/jobs${`?${string}` | `#${string}` | ''}` | `/main/settings${`?${string}` | `#${string}` | ''}` | `/main/tasks${`?${string}` | `#${string}` | ''}` | `/main/templates${`?${string}` | `#${string}` | ''}` | `/main/vendors${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_supabase-test`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/components/crew/CrewManager`; params?: Router.UnknownInputParams; } | { pathname: `/main/add-job`; params?: Router.UnknownInputParams; } | { pathname: `/main/edit-tabs`; params?: Router.UnknownInputParams; } | { pathname: `/main`; params?: Router.UnknownInputParams; } | { pathname: `/main/jobs`; params?: Router.UnknownInputParams; } | { pathname: `/main/settings`; params?: Router.UnknownInputParams; } | { pathname: `/main/tasks`; params?: Router.UnknownInputParams; } | { pathname: `/main/templates`; params?: Router.UnknownInputParams; } | { pathname: `/main/vendors`; params?: Router.UnknownInputParams; } | `/crew/job/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/job/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/job/${Router.SingleRoutePart<T>}/notes${`?${string}` | `#${string}` | ''}` | `/job/${Router.SingleRoutePart<T>}/send-links${`?${string}` | `#${string}` | ''}` | { pathname: `/crew/job/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/job/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/job/[id]/notes`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/job/[id]/send-links`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
